version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrix_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - JWT_SECRET=Zahard
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/agrix?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always

  mysql:
    image: mysql:8.0.32
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrix
      MYSQL_USER: root
      MYSQL_PASSWORD: root